services:
  app:
    image: caddy
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../docker/caddy/data:/data
      - ../docker/caddy/config:/config
